language: python
branches:
  only:
    - master
python:
  - "2.7"
# TODO: See if this helps
# cache:
#  directories:
#  - sugar-build

before_install:
  - pip install flake8
  - "git clone git://github.com/sugarlabs/sugar-build.git"
  - "cd sugar-build"
  - "./osbuild pull"
  - "./osbuild shell"
  - "build"

install: 
  - cd sugar-build/activities/
  - git clone https://github.com/davelab6/edit-fonts-activity.git edit-fonts.activity

script: 
  - flake8 sugar-build/activities/edit-fonts.activity

after_success:
# TODO: Set up coveralls
# - coveralls
  - python setup.py dist_xo
  - cd ~; ls -alFR

# TODO Set this up to auto-deloy tagged commits to the github releases page
# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#    tags: true
